// <auto-generated />
using System;
using EventService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EventService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(EventDbContext))]
    partial class EventDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EventService.Domain.Entities.Event", b =>
            {
                b.Property<Guid>("Id").HasColumnName("id").HasColumnType("uuid");
                b.Property<DateTime>("CreatedAt").HasColumnName("created_at").HasColumnType("timestamp with time zone");
                b.Property<DateTime>("Date").HasColumnName("date").HasColumnType("timestamp with time zone");
                b.Property<string>("Location").HasMaxLength(500).HasColumnName("location").HasColumnType("character varying(500)");
                b.Property<string>("Name").HasMaxLength(200).HasColumnName("name").HasColumnType("character varying(200)");
                b.Property<Guid>("OrganizerId").HasColumnName("organizer_id").HasColumnType("uuid");
                b.Property<string>("Status").HasMaxLength(20).HasColumnName("status").HasColumnType("character varying(20)");
                b.Property<DateTime?>("UpdatedAt").HasColumnName("updated_at").HasColumnType("timestamp with time zone");
                b.HasKey("Id");
                b.HasIndex("Date").HasDatabaseName("ix_events_date");
                b.HasIndex("OrganizerId").HasDatabaseName("ix_events_organizer_id");
                b.HasIndex("Status").HasDatabaseName("ix_events_status");
                b.ToTable("events");
            });

            modelBuilder.Entity("EventService.Domain.Entities.Zone", b =>
            {
                b.Property<Guid>("Id").HasColumnName("id").HasColumnType("uuid");
                b.Property<int>("AvailableCapacity").HasColumnName("available_capacity").HasColumnType("integer");
                b.Property<int>("Capacity").HasColumnName("capacity").HasColumnType("integer");
                b.Property<DateTime>("CreatedAt").HasColumnName("created_at").HasColumnType("timestamp with time zone");
                b.Property<Guid>("EventId").HasColumnName("event_id").HasColumnType("uuid");
                b.Property<string>("Name").HasMaxLength(100).HasColumnName("name").HasColumnType("character varying(100)");
                b.Property<decimal>("Price").HasPrecision(10, 2).HasColumnName("price").HasColumnType("numeric(10,2)");
                b.HasKey("Id");
                b.HasIndex("EventId").HasDatabaseName("ix_zones_event_id");
                b.ToTable("zones");
            });

            modelBuilder.Entity("EventService.Domain.Entities.Zone", b =>
            {
                b.HasOne("EventService.Domain.Entities.Event", null)
                    .WithMany("Zones")
                    .HasForeignKey("EventId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("EventService.Domain.Entities.Event", b =>
            {
                b.Navigation("Zones");
            });
#pragma warning restore 612, 618
        }
    }
}
